using System.Threading.Tasks;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using System.Threading;
using BehaviorTrees.Nodes;
using SandBox.GauntletUI.AutoGenerated1;

namespace BehaviorTreeWrapper.Tasks
{
    public class PrintQuickMessageTask : BTTask
    {
        private readonly string message;
        public PrintQuickMessageTask(string message) : base() { this.message = message; }
        public override BTNode Execute()
        {
            MBInformationManager.AddQuickInformation(new TextObject(message, null));
            return Parent;
        }
    }
}
